INSERT INTO products (name, description, price, image, stock) VALUES
('Wireless Mouse', 'Ergonomic wireless mouse with USB receiver.', 4.99, 'images/sample1.png', 50),
('Bluetooth Speaker', 'Portable Bluetooth speaker with deep bass.', 12.99, 'images/sample2.png', 30),
('USB-C Charger', 'Fast 18W USB-C wall charger.', 6.99, 'images/sample3.png', 100),
('Noise Cancelling Headphones', 'Over-ear headphones with active noise cancellation.', 29.99, 'images/sample4.png', 25),
('Smart Fitness Band', 'Waterproof fitness tracker with heart rate monitor.', 14.99, 'images/sample5.png', 60),
('Desk Lamp', 'LED desk lamp with touch controls and adjustable brightness.', 7.99, 'images/sample6.png', 40),
('Laptop Stand', 'Aluminum adjustable laptop stand for desk.', 9.99, 'images/sample7.png', 35),
('32GB Flash Drive', 'High-speed USB 3.0 32GB flash drive.', 5.49, 'images/sample8.png', 75),
('Wireless Keyboard', 'Slim wireless keyboard with silent keys.', 10.99, 'images/sample9.png', 40),
('Smartphone Tripod', 'Flexible tripod for smartphones and cameras.', 8.49, 'images/sample10.png', 20),
('Coffee Mug', 'Ceramic coffee mug with spill-proof lid.', 3.99, 'images/sample11.png', 100),
('Notebook', 'A5 lined notebook (100 pages).', 2.49, 'images/sample12.png', 200),
('Power Bank 10000mAh', 'Ultra slim 10000mAh USB power bank.', 13.99, 'images/sample13.png', 25),
('Portable Fan', 'Rechargeable mini portable fan.', 4.79, 'images/sample14.png', 90),
('Wireless Earbuds', 'Bluetooth 5.0 wireless earbuds with charging case.', 17.99, 'images/sample15.png', 35),
('HDMI Cable', '2m high-speed HDMI cable.', 2.99, 'images/sample16.png', 60),
('Smart LED Bulb', 'WiFi-enabled color-changing LED bulb.', 6.29, 'images/sample17.png', 50),
('Phone Holder', 'Adjustable phone holder for desk and car.', 3.69, 'images/sample18.png', 80),
('Backpack', 'Durable water-resistant laptop backpack.', 24.99, 'images/sample19.png', 15),
('USB Desk Fan', 'Silent USB-powered desk fan.', 5.99, 'images/sample20.png', 50);